# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pred_k <- function(x_mean_square_kK, query_data, x_mean_kK, N_k) {
    .Call('_SIGNAL_pred_k', PACKAGE = 'SIGNAL', x_mean_square_kK, query_data, x_mean_kK, N_k)
}

